[package]
name = "durable-sqlx"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stream = "0.3.5"
durable-core = { path = "../durable-core" }
futures-core = "0.3.30"
futures-util = "0.3.30"
log = "0.4.22"
serde = "1.0.204"

sqlx = { version = "0.8.0", default-features = false }
sqlx-core = { version = "0.8.0", default-features = false }
url = "2.5.2"

[dev-dependencies]
durable = { path = "../durable", features = ["sqlx"] }
