[package]
name = "durable-test-workflows"
version = "0.0.0"
edition = "2021"
license = { workspace = true }
publish = false

[dependencies]
durable = { workspace = true, features = ["http", "sqlx"] }
