[package]
name = "durable-test-workflows"
version = "0.0.0"
edition = "2021"
license = { workspace = true }
publish = false

[lib]
test = false

[dependencies]
anyhow = "1.0"

durable = { workspace = true, features = ["http", "sqlx"] }
