[package]
name = "durable-http"
version = "0.1.0"
edition = "2021"

[dependencies]
durable-core = { path = "../durable-core" }

http = "1.0"
http-serde-ext = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7"
url = { version = "2.5.2", features = ["serde"] }
chrono = "0.4"
