[package]
name = "xtask"
version = "0.0.0"
edition = "2021"
license = { workspace = true }
publish = false

[dependencies]
durable-bindgen = { workspace = true }
durable-migrate = { workspace = true, features = ["migrate"] }

anyhow = "1.0.102"
cargo_metadata = "0.23.1"
clap = { version = "4.6.0", features = ["derive"] }
dotenvy = "0.15.7"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.50.0", features = ["rt", "macros", "signal", "process"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
xshell = "0.2.7"
tracing = "0.1.44"
libc = "0.2.183"
glob = "0.3.3"
scopeguard = "1.2.0"

[dependencies.sqlx]
version = "0.9"
default-features = false
features = ["json", "postgres", "runtime-tokio", "tls-rustls"]
