[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
durable-bindgen = { path = "../durable-bindgen" }

clap = { version = "4.5.11", features = ["derive"] }
serde = { version = "1.0.204", features = ["derive"] }
anyhow = "1.0.86"
xshell = "0.2.6"
serde_json = "1.0.121"
