
[alias]
xtask = "run -p xtask --"
durable = "run -p durable-cli --bin durable --"

[registries]
iop-systems = { index = "sparse+http://storage.googleapis.com/systemslab-cargo/" }

[env]
DURABLE_DEVELOPMENT = "1"
