package durable:core@2.2.0;

world imports {
    import core;
    import http;
    import sql;
    import notify;

    import wasi:cli/environment@0.2.0;
    import wasi:cli/exit@0.2.0;
    import wasi:cli/stdin@0.2.0;
    import wasi:cli/stdout@0.2.0;
    import wasi:cli/stderr@0.2.0;
    export wasi:cli/run@0.2.0;

    include wasi:io/imports@0.2.0;
    include wasi:clocks/imports@0.2.0;
    include wasi:filesystem/imports@0.2.0;
    include wasi:random/imports@0.2.0;
}

world import-core {
    import core;
    import notify;
}

world import-http {
    import http;
}

world import-sql {
    import sql;
}
