
interface notify {
    use wasi:clocks/wall-clock@0.2.0.{datetime};

    /// A notification event.
    record event {
        /// The wall-clock time at which this notification was created.
        created-at: datetime,

        /// The name of the event itself.
        event: string,

        /// JSON-encoded data associated with the event.
        data: string,
    }

    /// Attempt to read the next available notification, if there is one.
    // notification: func() -> option<event>;

    /// Read the next available notification, blocking until one is available.
    notification-blocking: func() -> event;

    /// Errors that can occur as when attempting to notify another task.
    @since(version = 2.2.0)
    variant notify-error {
        /// There is no task with the requested task id.
        task-not-found,

        /// There is a task with the requested id, but it is no longer running.
        task-dead,

        /// Other unspecified errors that may occur, such as data not being valid JSON.
        other(string),
    }

    /// Emit a notification for a task.
    @since(version = 2.2.0)
    notify: func(task: s64, event: string, data: string) -> result<_, notify-error>;
}
