[package]
name = "durable"
version = "0.1.0"
edition = "2021"

[features]
default = ["regenerate"]
regenerate = ["dep:xshell"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
wit-bindgen = "0.28.0"

[build-dependencies]
xshell = { version = "0.2.6", optional = true }
