[package]
name = "durable"
version = "0.1.0"
edition = "2021"

[features]
default = ["sqlx"]

http = ["dep:durable-http"]
sqlx = ["dep:sqlx", "dep:chrono"]

[dependencies]
durable-core = { path = "../durable-core" }
durable-http = { path = "../durable-http", optional = true }

serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["raw_value"] }
wit-bindgen-rt = "0.28.0"

chrono = { version = "0.4.38", optional = true }

[dependencies.sqlx]
version = "0.8.0"
default-features = false
optional = true

[[example]]
name = "hello-world"

[[example]]
name = "http-request"
required-features = ["http"]
