
[package]
name = "durable-runtime"
version = "0.8.0"
edition = "2021"
license = { workspace = true }
publish = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
description = "Runtime for durable workflows"

[features]
# Enable the use of tokio-console with the runtime CLI.
#
# This doesn't do much unless --cfg tokio_unstable is included in rustflags.
tokio-console = ["dep:console-subscriber", "tokio/tracing"]

[dependencies]
durable-migrate = { workspace = true, features = ["migrate"] }

ahash = "0.8.12"
anyhow = "1.0.102"
anymap3 = "1.0.1"
async-stream = "0.3.6"
async-trait = "0.1.89"
cache-compute = "0.3.0"
cfg-if = "1.0.4"
chrono = { version = "0.4.44", features = ["serde"] }
clap = { version = "4.6", optional = true, features = ["derive", "env"] }
console-subscriber = { version = "0.5.0", optional = true }
derive_setters = "0.1.9"
ipnetwork = "0.20.0"
futures-concurrency = "7.7.1"
futures-util = "0.3.32"
getrandom = { version = "0.4.2", features = ["std"] }
http = "1.4.0"
humantime = "2.3.0"
log = "0.4.29"
parking_lot = "0.12.5"
pin-project = "1.1.11"
rand = "0.10.0"
reqwest = "0.13.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.149", features = ["raw_value"] }
sha2 = "0.10.9"
slab = "0.4.12"
tokio = { version = "1.50.0", features = ["macros", "sync", "rt-multi-thread"] }
tracing = "0.1.44"
uluru = "3.1.0"
uuid = { version = "1.22.0", features = ["serde"] }
wasmtime = { workspace = true }
url = "2.5.8"
metrics = "0.24.3"

[dependencies.sqlx]
version = "0.8.6"
features = [
    "postgres",
    "runtime-tokio",
    "tls-rustls",
    "chrono",
    "uuid",
    "ipnetwork"
]

[dependencies.sqlx-postgres]
version = "0.8.6"
features = ["offline"]

[dependencies.tracing-subscriber]
version = "0.3"
optional = true
features = ["fmt", "env-filter"]

[target.'cfg(unix)'.dependencies]
backtrace-on-stack-overflow = { version = "0.3", optional = true }

[dev-dependencies]
toml = "1.0"

[build-dependencies]
durable-migrate = { workspace = true }

anyhow = "1.0.102"
