name: cargo
on:
  push:
    branches:
      main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1
      - uses: Swatinem/rust-cache@v2
      - uses: swlynch99/cargo-sweep-action@v1
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest,cargo-component

      - name: create test database
        run: cargo run --bin xtask --profile dev-ci -- dev -d

      - name: cargo nextest run
        run: |
          cargo nextest run         \
            --locked                \
            --all-targets           \
            --all-features          \
            --no-fail-fast          \
            --success-output final  \
            --cargo-profile dev-ci  \
            --final-status-level skip
        shell: bash
      
      - name: doctests
        run: |
          cargo test --doc  \
            --all-features  \
            --locked
        shell: bash

  # Verify that the crate builds without the database being available.
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: swlynch99/cargo-sweep-action@v1

      - name: cargo check
        run: cargo check --all-features --all-targets --profile dev-ci

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: rustfmt
        run: |
          cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - uses: swlynch99/cargo-sweep-action@v1
      - uses: taiki-e/install-action@v2
        with:
          tool: clippy-sarif,sarif-fmt,cargo-deduplicate-warnings

      - name: cargo clippy
        run: |
          cargo clippy --all-targets --all-features --message-format json --profile dev-ci \
            | cargo deduplicate-warnings \
            | clippy-sarif      \
            | tee clippy.sarif  \
            | sarif-fmt
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        with:
          name: clippy-sarif
          path: clippy.sarif

  clippy-upload:
    if: github.event_name == 'pull_request' || github.ref == 'reads/heads/main'
    runs-on: ubuntu-latest
    needs:
      - clippy
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: clippy-sarif
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: clippy.sarif

  check-success:
    name: verify all tests pass
    runs-on: ubuntu-latest
    if: always()
    needs:
      - test
      - check
      - clippy
      - rustfmt

    steps:
      - name: fail if any dependencies failed
        if: contains(needs.*.result, 'failure')
        shell: bash
        run: exit 1
      - name: no-op
        run: echo "All checks passed!"
